In [1]:
import pandas as pd

In [6]:
df_benefits = pd.read_csv("data/Benefits_Cost_Sharing_PUF.csv")

/usr/local/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (9,12,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
df_benefits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1859159 entries, 0 to 1859158
Data columns (total 24 columns):
 #   Column               Dtype
---  ------               -----
 0   BusinessYear         int64
 1   StateCode            object
 2   IssuerId             int64
 3   SourceName           object
 4   ImportDate           object
 5   StandardComponentId  object
 6   PlanId               object
 7   BenefitName          object
 8   CopayInnTier1        object
 9   CopayInnTier2        object
 10  CopayOutofNet        object
 11  CoinsInnTier1        object
 12  CoinsInnTier2        object
 13  CoinsOutofNet        object
 14  IsEHB                object
 15  IsCovered            object
 16  QuantLimitOnSvc      object
 17  LimitQty             float64
 18  LimitUnit            object
 19  Exclusions           object
 20  Explanation          object
 21  EHBVarReason         object
 22  IsExclFromInnMOOP    object
 23  IsExclFromOonMOOP    object
dtypes: float64(1), int64(2), object(21)
memory usage: 340.4+ MB

In [8]:
df_benefits.head(5)

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,StandardComponentId,PlanId,BenefitName,CopayInnTier1,CopayInnTier2,...,IsEHB,IsCovered,QuantLimitOnSvc,LimitQty,LimitUnit,Exclusions,Explanation,EHBVarReason,IsExclFromInnMOOP,IsExclFromOonMOOP
0,2022,AK,21989,HIOS,2021-08-19 15:35:03,21989AK0030001,21989AK0030001-00,Routine Dental Services (Adult),Not Applicable,NaN,...,NaN,Covered,Yes,1000.0,Dollars per Year,NaN,$1000 annual maximum plan payment limit combin...,Not EHB,Yes,Yes
1,2022,AK,21989,HIOS,2021-08-19 15:35:03,21989AK0030001,21989AK0030001-00,Dental Check-Up for Children,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,See policy for additional limitations,Substantially Equal,No,No
2,2022,AK,21989,HIOS,2021-08-19 15:35:03,21989AK0030001,21989AK0030001-00,Basic Dental Care - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,NaN,NaN,No,No
3,2022,AK,21989,HIOS,2021-08-19 15:35:03,21989AK0030001,21989AK0030001-00,Orthodontia - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,Only medically necessary orthodontia is covered,Substantially Equal,No,No
4,2022,AK,21989,HIOS,2021-08-19 15:35:03,21989AK0030001,21989AK0030001-00,Major Dental Care - Child,Not Applicable,NaN,...,Yes,Covered,NaN,NaN,NaN,NaN,NaN,NaN,No,No

In [9]:
df_rate = pd.read_csv("data/Rate_PUF.csv")

In [10]:
df_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498402 entries, 0 to 2498401
Data columns (total 20 columns):
 #   Column                                     Dtype
---  ------                                     -----
 0   BusinessYear                               int64
 1   StateCode                                  object
 2   IssuerId                                   int64
 3   SourceName                                 object
 4   ImportDate                                 object
 5   RateEffectiveDate                          object
 6   RateExpirationDate                         object
 7   PlanId                                     object
 8   RatingAreaId                               object
 9   Tobacco                                    object
 10  Age                                        object
 11  IndividualRate                             float64
 12  IndividualTobaccoRate                      float64
 13  Couple                                     float64
 14  PrimarySubscriberAndOneDependent           float64
 15  PrimarySubscriberAndTwoDependents          float64
 16  PrimarySubscriberAndThreeOrMoreDependents  float64
 17  CoupleAndOneDependent                      float64
 18  CoupleAndTwoDependents                     float64
 19  CoupleAndThreeOrMoreDependents             float64
dtypes: float64(9), int64(2), object(9)
memory usage: 381.2+ MB

In [12]:
df_rate.sample(5)

,BusinessYear,StateCode,IssuerId,SourceName,ImportDate,RateEffectiveDate,RateExpirationDate,PlanId,RatingAreaId,Tobacco,Age,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents
1631970,2022,WI,81335,HIOS,2021-05-13 01:00:50,2022-01-01,2022-03-31,81335WI0120001,Rating Area 3,No Preference,29,1029.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363664,2022,FL,30252,HIOS,2021-11-04 01:01:10,2022-01-01,2022-12-31,30252FL0020092,Rating Area 43,Tobacco User/Non-Tobacco User,58,1050.18,1260.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485442,2022,TX,92388,HIOS,2021-05-14 01:00:27,2022-01-01,2022-03-31,92388TX0190001,Rating Area 3,No Preference,56,23.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1057373,2022,NC,82612,HIOS,2021-07-08 01:00:38,2022-01-01,2022-12-31,82612NC0010001,Rating Area 13,No Preference,18,42.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1351672,2022,TX,29418,HIOS,2021-08-17 01:01:36,2022-01-01,2022-12-31,29418TX0160104,Rating Area 11,Tobacco User/Non-Tobacco User,58,1022.75,1176.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_rate["Age"].value_counts()

0-14             48970
15               48970
42               48970
43               48970
44               48970
45               48970
46               48970
47               48970
48               48970
49               48970
50               48970
51               48970
52               48970
53               48970
54               48970
55               48970
56               48970
57               48970
58               48970
59               48970
60               48970
61               48970
62               48970
63               48970
64 and over      48970
41               48970
40               48970
39               48970
26               48970
16               48970
17               48970
18               48970
19               48970
20               48970
21               48970
22               48970
23               48970
24               48970
25               48970
27               48970
38               48970
28               48970
29               48970
30               48970
31               48970
32               48970
33               48970
34               48970
35               48970
36               48970
37               48970
Family Option      932
Name: Age, dtype: int64